import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { QrProvider } from "./context/HistoryContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{ marginTop: "20px", textAlign: "center" }}>
          <div style={{ marginTop: "10px", flexDirection: "row" }}>
            <Link href="/history">History</Link>
            <br />
            <Link href="/">Home</Link>
          </div>
        </nav>
        <QrProvider>{children}</QrProvider>
      </body>
    </html>
  );
}
